### ISSUE TITLE
Will the full code for evaluation available?

### ISSUE THREAD

**Issue by bangawayoo** [GAIR-NLP/alignment-for-honesty#1]
Hi! 
Thank you for the impressive work and for releasing the code!

I noticed that I had to complete  `evaluation/triviaqa_nonambigqa_evaluation.py` in order to reproduce the numbers for the paper. 
Will you make the full code (script) available in the future? 

Thanks.

**Comment by bangawayoo** [comment]
@ayyyq @neubig  @EthanC111 
Hi, do you have any updates on this?

Thanks.

**Comment by ayyyq** [comment]
Hi, I sincerely apologize for the delayed response. Currently, the code requires you to complete a segment to **generate responses using the OpenAI API**. You can choose your preferred method, such as LangChain, or refer to [this script](https://github.com/GAIR-NLP/OPO/blob/main/script/gpt_usage.py). We have already provided all the necessary prompts and data processing code.

For the evaluation of free-form QA tasks, to reduce API costs, we have combined a rule-based approach (step 2) and ChatGPT evaluation (step 3) as described in [this section](https://github.com/GAIR-NLP/alignment-for-honesty/blob/5357ef8700e12b506e1e18685eded3fb082940fe/evaluation/triviaqa_nonambigqa_evaluation.py#L155-L162).

Thank you for your feedback. We will consider refactoring the evaluation code within a month to make it more user-friendly. In the meantime, if you have any questions, please feel free to contact us. Thank you!
